[FEAT] - Save settings
wisemen-digital/vue-project-template pull request #108
Opened 2024-12-28 09:05 UTC by JeroenVanC

### Context

### Description

### Checklist

- [ ] I have added tests to cover this change (if necessary)

### Screenshots (optional)

2024-12-30 08:55 UTC, maltsavkiryl approved these changes

2024-12-30 08:55 UTC, maltsavkiryl commented on src/components/layout/sidebar/AppSidebar.vue
> +  authUser: User
`user: User`

2024-12-30 08:55 UTC, maltsavkiryl commented on src/components/layout/sidebar/AppSidebarBottom.vue
> +  authUser: User
user: User

2024-12-30 08:55 UTC, maltsavkiryl commented on src/components/layout/sidebar/AppSidebarUserProfile.vue
> +  authUser: User
user: User

2024-12-30 09:39 UTC, maltsavkiryl requested changes

2024-12-30 09:39 UTC, maltsavkiryl commented on src/modules/settings/features/application/components/keyboard-shortcuts/SettingApplicationOverviewKeyboardShortcut.vue
>  const computedValue = computed<boolean>({
moet ge die value niet van de backend ophalen?

2025-01-02 09:06 UTC, Tanya-Amber-L approved these changes

2025-01-02 09:06 UTC, Tanya-Amber-L commented on src/components/layout/sidebar/AppSidebarUserProfile.vue
> +  `${props.authUser?.firstName?.[0] ?? 0}${props.authUser?.lastName?.[0] ?? 0}`
Wouldn't this display the actual number 0 if missing first or last name? Shouldn't this be `?? ''` instead of `?? 0`

2025-01-02 09:06 UTC, Tanya-Amber-L commented on src/stores/auth.store.ts
> +  // async function getAuthUserSubject(): Promise<UserSubject> {
Commented code?

2025-01-03 11:48 UTC, JeffreyNijs commented on src/modules/settings/features/application/components/keyboard-shortcuts/SettingApplicationOverviewKeyboardShortcut.vue
>  const computedValue = computed<boolean>({
Hij heeft wel een punt, waarom staan die prefs niet in de backend?

2025-01-03 11:48 UTC, JeffreyNijs approved these changes

2025-01-30 09:20 UTC, merged