[Feature] Template cleanup
wisemen-digital/vue-project-template pull request #58
Opened 2024-05-10 12:12 UTC by maltsavkiryl

2024-05-10 12:17 UTC, wouterlms requested changes

2024-05-10 12:17 UTC, wouterlms commented on src/modules/auth/api/services/auth.service.ts
>        url: '/api/auth/userinfo',
ik denk dat hier `/api` ook nog weg moet

2024-05-10 12:17 UTC, wouterlms commented on src/utils/paginationDtoBuilder.util.ts
> +  public withLimit(perPage: number): PaginationDtoBuilder<TFilterSchema> {
Ik zou dat niet `withLimit` noemen want de spec zegt `withSize`. Ik vind limit sowieso een verwarrende naam

2024-05-10 13:19 UTC, Robbe95 commented on src/App.vue
> +  logInfo('Application started', {
Dit wilt ge niet op production doen denk ik?

2024-05-10 14:24 UTC, maltsavkiryl commented on src/App.vue
> +  logInfo('Application started', {
Waarom niet? Anders weet ge nooit 100% zeker welke versie deployed is

2024-05-20 04:27 UTC, JeffreyNijs approved these changes
zie comment wouter

2024-05-30 15:23 UTC, JeffreyNijs approved these changes
lgtm

2024-05-30 15:23 UTC, JeffreyNijs commented on src/components/app/ThemeProvider.vue
> +const currentTheme = computed<ThemeConstant | null>(() => theme.current.value)
Is die tussen-computed wel nodig?

2024-05-30 15:32 UTC, wouterlms approved these changes

2024-05-30 15:34 UTC, merged